default_language_version:
  python: python3.7

minimum_pre_commit_version: "2.6.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: .*\.json-result
      - id: check-json
      - id: check-yaml
        args:
          - "--unsafe"  # needed for parsing CFN

  - repo: https://github.com/timothycrosley/isort
    rev: 5.3.2
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        # stable release of black does not respect exclude when file is explicitly provided
        # waiting for this to be released - https://github.com/psf/black/pull/1032
        exclude: (^npm/|^quickstarts/|^runway/aws_sso_botocore/)

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        args:
          - "--docstring-convention=all"  # TODO move to setup.cfg when dropping python 2
        additional_dependencies:
          - flake8-docstrings
