---
language: python
addons:
  apt:
    packages:
      - pandoc
      - sed
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - "pip install Send2Trash awacs 'awscli<1.16.0' docopt flake8 \
     flake8-docstrings pep8-naming future pyhcl pylint typing yamllint \
     zgitignore 'stacker~=1.4' 'botocore<1.11.0' 'boto3~=1.7.0' pylint \
     'pydocstyle<=3.0.0'"
script: make travis
