---
language: python
addons:
  apt:
    packages:
      - pandoc
      - sed
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  # astroid & pylint pinned back to fix
  # https://github.com/PyCQA/pylint/issues/3134
  - "pip install Send2Trash awacs 'awscli<1.16.0' docopt flake8 \
     flake8-docstrings pep8-naming future 'mock~=3.0.5' pyhcl pyOpenSSL \
     'pylint<=2.3.1' requests typing yamllint zgitignore 'stacker~=1.7' \
     'botocore<1.11.0' 'boto3~=1.7.0' 'pydocstyle<=3.0.0' cfn-lint \
     'astroid<=2.2.0'"
script: make travis
