service: serverless-test-pzmssz

provider:
  name: aws
  runtime: nodejs12.x

functions:
  helloWorld:
    handler: frontend/func1/handler.hello

  helloWorld2:
    handler: backend/func2/handler.hello2
